# Generated by Django 5.0.1 on 2024-01-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmation_token',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(default='', max_length=64),
        ),
    ]
