# Generated by Django 5.0.1 on 2024-02-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_blog_likes'),
        ('userauth', '0005_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_blogs',
            field=models.ManyToManyField(blank=True, related_name='likes', to='main.blog'),
        ),
    ]
