# Generated by Django 4.2.11 on 2024-03-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_userprofile_liked_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_confirmation_token',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(default='', max_length=128),
        ),
    ]
