version: '3'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/django
      - static_files:/django/staticfiles
      - media_files:/django/media
    command: gunicorn core.wsgi --bind 0.0.0.0:8000 --reload
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend/blogProject-frontend
    volumes:
      - react_build:/react/dist

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - react_build:/var/www/react
      - static_files:/home/app/staticfiles
      - media_files:/home/app/media
    depends_on:
      - frontend
      - backend

volumes:
  react_build:
  static_files:
  media_files:
