# Generated by Django 5.0.1 on 2024-01-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_content'),
        ('userauth', '0004_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='userauth.userprofile'),
        ),
    ]
