# Generated by Django 5.0.1 on 2024-01-31 05:46

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=main.models.upload_to, verbose_name='Image'),
        ),
    ]
