# Generated by Django 5.0.1 on 2024-01-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_image'),
        ('userauth', '0004_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='userauth.userprofile'),
        ),
    ]
