# Generated by Django 5.0.1 on 2024-01-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_blog_likes'),
        ('userauth', '0004_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(default=[], to='userauth.userprofile'),
        ),
    ]
