# Generated by Django 5.0.1 on 2024-02-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog_author_alter_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
